<?php

declare(strict_types=1);

namespace OC\FilesMetadata;

use OCP\DB\QueryBuilder\IQueryBuilder;
use OCP\FilesMetadata\IFilesMetadata;
use OCP\FilesMetadata\IFilesMetadataQueryHelper;

class FilesMetadataQueryHelper implements IFilesMetadataQueryHelper {

	public function __construct() {
	}

	public function linkedToFileId(
		IQueryBuilder $queryBuilder,
		string $fileTableAlias,
		string $fileIdField
	): void {
		// leftJoin metadata in fileid=fileid
		// add json to the select in specific templated alias
	}

	public function limitToSingleMetadata(
		IQueryBuilder $queryBuilder,
		string $fileTableAlias,
		string $fileIdField,
		string $metadataKey,
		string $metadataValue,
		bool $selectMetadata = false
	): void {
		// right join in fileId=fileId
		// add json to the select in specific templated alias if $selectMetadata
		// andWhere with metadataKey and metadataValue
	}

	/**
	 * @param array $data
	 *
	 * @return IFilesMetadata
	 */
	public function extractMetadata(array $data): IFilesMetadata {
		$json = '[]'; // from $data, in an alias field generated by limitToSingleMetadata()
		$fileId = 1; // from $data, in an alias field generated by limitToSingleMetadata()

		$metadata = new FilesMetadata($fileId);
		$metadata->import($json);

		return $metadata;
	}

}
